[package]
name = "wlancfg"
version = "0.1.0"
license = "BSD-3-Clause"

[dependencies]
failure = "0.1"
fidl = "0.1"
fuchsia-app = "0.1"
fuchsia-async = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
garnet_lib_wlan_fidl = "0.1"
garnet_lib_wlan_fidl_service = "0.1"
