# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "wget-rs"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Tim Kilbourn <tkilbourn@google.com>"]
description = "Example client for the Fuchsia Network Service"

[dependencies]
failure = "0.1.1"
fidl = "0.1"
fuchsia-app = "0.1"
fuchsia-async = "0.1"
futures = "=0.2.0-alpha"
garnet_public_lib_network_fidl = "0.1"
garnet_public_lib_fsl_fidl = "0.1"
