[package]
name = "wlan-test-util"
version = "0.1.0"
authors = ["Tim Kilbourn <tkilbourn@google.com>"]

[dependencies]
failure = "0.1"
fdio = "0.2"
fidl = "0.1"
fidl_wlan_device = "0.1"
fuchsia-async = "0.1"
fuchsia-wlan-dev = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
