[package]
name = "fuchsia-vfs-watcher"
version = "0.1.0"
license = "BSD-3-Clause"

[dependencies]
fdio = "0.2"
fuchsia-async = "0.1"
fuchsia-zircon = "0.3"
futures = { version = "0.2.1", features = ["nightly"] }

[dev-dependencies]
tempdir = "0.3"
