[package]
name = "microorb"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Walbran <qwandor@google.com>"]
description = "Driver for USB microorb"
repository = "https://fuchsia.googlesource.com/garnet/"
build = "build.rs"

[lib]
name = "microorb"
crate-type = ["dylib"]

[dependencies]
fuchsia-ddk = { path = "../../../fuchsia-ddk" }
fuchsia-zircon = { path = "../../../fuchsia-zircon" }

[build-dependencies]
cc = "1.0"
